#!/usr/bin/env bash
# this fnction prints out infinitely with a function to redirect signals
sigterm()
{
	echo "I am invincible!!!"
}

trap 'sigterm' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
