#!/usr/bin/env bash
# shell script that prints "Best School" 10 times, changing at 9
count=1
while [ $count -lt 10 ]; do
	if [ $count = 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
echo "Best School"
